name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write  # Garante permissão para fazer commits

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Contribution Graph
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: mateuscotrim  # Substitua pelo seu usuário do GitHub
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Show git status
        run: git status

      - name: List generated files
        run: ls -l dist

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generated new Snake animation"
          branch: main  # Altere para 'master' se necessário
          file_pattern: dist/github-contribution-grid-snake.gif dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
